apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-dev
spec:
  source:
    repoURL: https://github.com/youruser/gitops-demo.git
    path: helm/flask-app
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  syncPolicy:
    automated: {}
